---
- name: Update apt packages
  become: true
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: Upgrade packages
  become: true
  apt:
    upgrade: yes
    
- name: install pm2
  npm:
    name: pm2
    global: yes